version: '3.7'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env.prod
    volumes:
      - db_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - db
    cap_add:
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
  api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env.prod
    ports:
      - 4000:${PORT}
    networks:
      - db
networks:
  db:
    driver: bridge

volumes:
  db_data:
